name: Continuous Integration

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  build:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Maven Verify
        run: mvn --no-transfer-progress --batch-mode --update-snapshots --fail-at-end clean verify
